### ISSUE TITLE
On change and After create MF doesn't fire

### ISSUE THREAD

**Issue by SergeJansen1985** [mendix/LabelSelector#11]
I've imported the widget in a Mx 7.2.0 project. Widget works fine, excepts that both the after create nor the on change microflow does not fire.

**Comment by JelteMX** [comment]
Are you sure you have downloaded the latest version of the widget? (4.4.1)

I have opened the test-project in this repository in Mendix 7.2.0 and it seems to work fine. If this issue still exists while you have the latest version from the AppStore, please file a ticket with Support (Label Selector has Extended Support)

**Comment by SergeJansen1985** [comment]
Yes, I've also tried an older version of the widget (v4.4) and this one works fine in the same project. So for now, the problem is solved for this project :) But I will file a ticket for the latest version.

**Comment by Andries-Smit** [comment]
We close the the outdated issue. Please open a support ticket with a good sample project if the issue is still at play. Cheers
