### ISSUE TITLE
Some characters are not displayed correctly

### ISSUE THREAD

**Issue by ssuijkerbuijk** [mendix/LabelSelector#15]
Characters & < > are not diplayed correctly when used.

& will become &amp;
< will become &lt;
> will become &gt;

**Comment by ssuijkerbuijk** [comment]
Characters & < > are not diplayed correctly when used.

& will become & a m p ;  (without the spaces)
< will become & l t ; (without the spaces)
> will become & g t ; (without the spaces)

**Comment by JelteMX** [comment]
Version [4.5.1](https://github.com/mendix/LabelSelector/releases/tag/v4.5.1) fixes these issues
