### ISSUE TITLE
Problem in 5.17

### ISSUE THREAD

**Issue by mkumpf** [mendix/LabelSelector#2]
Hi - it seems like the LabelSelector doesn't work in 5.17 - browser console errors are as follows:
![image](https://cloud.githubusercontent.com/assets/3680543/8500665/2e83daae-216c-11e5-8bf7-6d9bca2f7622.png)

Is this something you are working on?
Thanks,
Mike Kumpf

**Comment by RoelandSalij** [comment]
Mike, I'm not able to reproduce this in the test project. Are there other widgets in your project which might conflict on this widget? Especially other widgets using JQuery could cause this exception as they might overwrite the JQuery instance.

**Comment by mkumpf** [comment]
Roeland,

I resolved this yesterday and didn't have time to update this issue.  For details, see my forum posting here:  https://mxforum.mendix.com/questions/8416/Problem-with-Label-Selector

Thanks for the follow up.

Mike
